# Start all the storage containers locally without running the application inside docker
version: '2'
services:
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: chatserver
      POSTGRES_PASSWORD: chatserver
    ports:
      - "5432:5432"
    volumes:
      - ${HOME}/.chatserver/db/data:/var/lib/postgresql/data
